# -*- coding: utf-8 -*-
"""WorldsPowerfulPeople.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xAu90U3PhyGWH4YarlokmW5Haa-gr37Y
"""

import io

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

from google.colab import files
uploaded = files.upload()

#pip install "pandas<0.25.0"

#!pip install "pandas<0.25.0"

from io import StringIO

PowerfulPeople_Dataframe = pd.read_csv(io.BytesIO(uploaded['TheWorldsMostPowerfulPeople.csv']))
print(PowerfulPeople_Dataframe.head())

print(PowerfulPeople_Dataframe.columns)

columns_to_drop = ["NAME"]
(PowerfulPeople_Dataframe.drop(columns_to_drop, axis=1, inplace=True))
print(PowerfulPeople_Dataframe.head())

columns_to_drop2 = ["ORGANİZATİON"]
(PowerfulPeople_Dataframe.drop(columns_to_drop2, axis=1, inplace=True))
print(PowerfulPeople_Dataframe.head())

def Age_Group(row):
  curr_val = row["AGE"]
  if curr_val < 40:
    return "Less than 40"
  elif curr_val < 50:
    return "Less than 50"
  elif curr_val < 60:
    return "Less than 60"
  else: 
    return "Less than 90"

New_dataframe = (PowerfulPeople_Dataframe.apply(Age_Group, axis=1))

print(New_dataframe.head(10))

fig = px.bar(PowerfulPeople_Dataframe, x='RANK', y='AGE')
fig.show()

